version: "3.3"
services:
  db:
    build: ./database/
  
  app :
    build: ./app/
    depends_on: 
      - db

  dashboard:
    build: ./dashboard/
    depends_on: 
      - db
      - app 
    ports:
      - "8050:8050"
    
    
